// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node prisma/seed.js",
    // The following is an example of how to use a custom seed script with Prisma. You can replace it with your own implementation.
  },
  datasource: {
    url: env("POSTGRES_PRISMA_URL"),
  },
});
